### ISSUE TITLE
IVIF 问题请教

### ISSUE THREAD

**Issue by yidamyth** [iyume/image-fusion#2]
尊敬的作者感谢您的分享，让初学者收益很多。作为初学者部分地方自己有点儿疑惑，能否请教您一下。

1.损失函数，仅仅使用了fus和 vis 做像素级、SSIM、梯度的损失；我看部分论文都是考虑vis和ir 的损失；请问这是为什么呢，这个损失没有考虑 vi 部分，融合的图像能保证红外的结构信息吗

2.net.py模型中是没有使用 BN 层的，自己在实验的时候加不加 BN 层好像对融合结果差别特别大，能请问下作者 BN 层是否应该添加，需要添加到什么地方呢？

**Comment by iyume** [comment]
1. 你可能不太理解 AE 和 CNN，训练过程只是为了重建源图像，和图像的种类无关的。至于损失函数，其实 L2 都行，但是混合 SSIM 和梯度的话，训练速度会大大提升。

2. BN 层在 AE 结构中对图像重建影响很大，所以不添加。如果你需要 BN，可以去尝试 VAE(Variant Auto Encoder)，我没试过，也不知道 VAE 重建能力如何。

**Comment by yidamyth** [comment]
> 1. 你可能不太理解 AE 和 CNN，训练过程只是为了重建源图像，和图像的种类无关的。至于损失函数，其实 L2 都行，但是混合 SSIM 和梯度的话，训练速度会大大提升。
> 2. BN 层在 AE 结构中对图像重建影响很大，所以不添加。如果你需要 BN，可以去尝试 VAE(Variant Auto Encoder)，我没试过，也不知道 VAE 重建能力如何。

学长您好，特别感谢您的回复。作为新人可能有很多地方不太理解，您见谅。

①对于第一个问题我还是有点儿不太理解，对于图像融合来说得到融合图像确实是一个生成任务，生成的图像需要融合红外与可见光图像的特性。如果仅与可见光图像做损失的话，那么损失为零的情况就是与可见光图像像素一样、结构一样、梯度一样；我的意思是这样融合的图像就没有包含 IR 红外光图像的信息（没有用损失约束），那么它是如何很好的融合的呢，还能够生成并包含红外图像的结构信息。

②学长，我还有一个问题不太明白，一般训练模型我看论文都是基于 256-256 或者 128-128 的大小，测试的时候都是基于原图进行的。这是怎么操作的呢？如果是基于 CNN 那么可能对输入的大小没那么敏感，但是基于 Transformer 和固定大小的层，那么原图输入就没办法进行，因为大小不匹配。想请教下学长到底是怎么做的呢。

**Comment by iyume** [comment]
@YidaMyth 
1. 我还是那句话，你连论文大体思路没搞懂，也不懂 AE，就想着别人来给你解释？如果你对代码感兴趣那就去看代码，很多论文我也是看代码才看懂，自己看懂才是懂。
2. CNN 里如果涉及 Linear 层就需要固定输入的 “尺度”（宽高），如果不涉及那就一般只有 in_channels 和 out_channels。

> 一般训练模型我看论文都是基于 256-256 或者 128-128 的大小

我不知道你说的是哪些论文，但我敢保证 “图像融合” 课题（包括红外可见、曝光图像、多聚焦图像）的 90% 论文不会限制输入图像的尺度。训练时可能是用了图像分割，一般不会 resize。

> 如果是基于 CNN 那么可能对输入的大小没那么敏感，但是基于 Transformer 和固定大小的层，那么原图输入就没办法进行

这个问题其实有点复杂，但是有很多种处理方法（是不是 transformer 都差不多），Image Segmentation 的很多论文中都有类似的方法去解决精度的问题。最简单的办法就是不使用 Linear 层，Linear 很多时候其实用不到，用 Conv1d 就行。还有就是 context embedding，比如 stable diffusion 可以接受各种 embedding，文字、图像和语音，只要你保证 context 是 768 维（一般会使用 Linear 进行变换），就可以嵌入到输入中。

**Comment by yidamyth** [comment]
学长您好，特别感谢您的回复，一下几点我想要从我的角度解释一下。

一、
> 我不知道你说的是哪些论文，但我敢保证 “图像融合” 课题（包括红外可见、曝光图像、多聚焦图像）的 90% 论文不会限制输入图像的尺度。训练时可能是用了图像分割，一般不会 resize。

在您的config 文件中看见您是基于MSRS 数据集进行的研究，由于这个数据集是预处理过后的因此输入的大小是相同的。不用额外的处理要做并行运算也可以直接计算。但是有部分红外与可见光数据集大小是不同的比如 TNO 和RoadScene大小就是不同的，那么就需要处理，直接原大小输入就不行。我后来了解到确实不是用的 resize 操作，而是基于裁剪成固定大小的图像比如 256-256 作为训练集。
您是基于的卷积操作，而且图像大小为偶数时那么编码和解码完全不需要考虑图像的大小关系（下采样和上采样都能够很好的还原图像大小）。在不考虑额外 padding 下，如果是奇数那么下采样可能会造成图像大小无法对应的情况（比如 7 可能下采样得到 3 还原为 6）。那么我了解到最好的办法就是尽可能不下采样直接原图大小操作（只改变维度），或者需要下采样时保证输入维度相同且均为偶数就行。
训练时基于原图裁剪的 256-256 大小，测试时基于原图进行。

二、
> 这个问题其实有点复杂，但是有很多种处理方法（是不是 transformer 都差不多），Image Segmentation 的很多论文中都有类似的方法去解决精度的问题。最简单的办法就是不使用 Linear 层，Linear 很多时候其实用不到，用 Conv1d 就行。还有就是 context embedding，比如 stable diffusion 可以接受各种 embedding，文字、图像和语音，只要你保证 context 是 768 维（一般会使用 Linear 进行变换），就可以嵌入到输入中。

我是基于的原始 Transformer 确实会出现维度不一样的情况，原来我怎么都想不通如何训练基于 256 大小的图像，在测试时确是基于原图进行测试的。后面我了解到比如 Swintransformer 能够应对任意大小的输入，传入时会自动匹配维度并输出原始维度。因此我就知道这部分是如何解决的了。当然基于 CNN 的操作仅卷积操作的话不会改变图像大小。一般是基于裁剪的大小比如 256-256 进行模型训练，测试时直接基于原图得到融合结果。

三、

> * 我还是那句话，你连论文大体思路没搞懂，也不懂 AE，就想着别人来给你解释？如果你对代码感兴趣那就去看代码，很多论文我也是看代码才看懂，自己看懂才是懂。
> * CNN 里如果涉及 Linear 层就需要固定输入的 “尺度”（宽高），如果不涉及那就一般只有 in_channels 和 out_channels。

①是这样的学长，我是以关键词检索到的代码，您分享的代码中没有对应的文章链接，因此有些细节我第一次看可能了解的没有那么详细。首先我看到了代码中的 arch1.png；对于输入是 input 并没有标明是红外还是可见光的图像，这张图没有输出，对损失如何做的不能很清楚理解到；因此对于红外与可见光图像融合中，我自己以为这儿是输入的红外与可见光图像来共同训练这个 编-解码器。

②arch2.png中，这里有 ir 和 vi 两个输入，而且这个编解码器并没有连在一起或者标注参数是冻结的，因此我按照这种双分支的理解以为是图 1 的扩充分别训练红外与可见光图像。因此照成了在前面训练编-解码器时仅用了可见光作为输入来训练的不理解。

③在arch2.png中，橙色的线标注的是 gradient transfer，绿色的线也是标注的 gradient transfer；为什么上下都是一样的，因此就不是很理解整个过程。当然通过后面对代码的学习，了解到是先用 VI 可见光图像训练的编解码器，然后固定参数。分别输入 IR 和 VI 图像到编码器，生成特征图和梯度；然后基于 max 对应值最大的原则融合图像特征和梯度在拼接；最后在基于固定的解码器对其进行解码得到融合结果。当然这时候在看图的话，就知道橙色的线是 gradient transfer；绿色的线应该是 feature transfer 或者 ir-vis transfer。

④也许是因为自己看论文比较少，更多的是关注双分支或者特征融合在重建的融合模型。对于这样的模型和融合方式对自己来说比较新，第一次看会不太能理解。

最后特别感谢您的回复，以后自己会更加关注于代码本身的学习，并不断提升阅读和理解能力。

**Comment by iyume** [comment]
> 但是有部分红外与可见光数据集大小是不同的比如 TNO 和RoadScene大小就是不同的，那么就需要处理，直接原大小输入就不行。我后来了解到确实不是用的 resize 操作，而是基于裁剪成固定大小的图像比如 256-256 作为训练集。

我论文里面复现了 6、7 篇论文做对比，并没有你说的情况，请你自己研究。

> 我是以关键词检索到的代码，您分享的代码中没有对应的文章链接

链接就贴在 github 主页上，看不到在简介的下面？

另外，架构图不是我画的，当时感觉画的差不多就放上去了。

没事我就 close 了。
